language: python

python:
  - "2.6"
  - "2.7"

install:
  - "pip install -r requirements.txt"

script: "nosetests benchmark"

after_success:
  - pip install coverage
  - pip install coveralls
  - pylint --rcfile=pylint.rc benchmark/*.py
  - nosetests benchmark --with-coverage
  - coveralls

branches:
  only:
    - master

notifications:
  email: false
