language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements.txt"
script: "nosetests benchmark"
branches:
  only:
    - master
notifications:
  email:
    - libsora25@gmail.com